### ISSUE TITLE
a bug when you can't sell some items

### ISSUE THREAD

**Issue by AttarGangster2** [CabooseSayzWTF/RDR1-Switch-and-PS4-Mod-Menu#1]
this bug is currently occurred when you triggered the max money cheat on this trainer and i can't even pass the mission called John Marston and Son when you need to sell an Elk meat, it says selled when i try to sell the Elk meat but the objective is still trying to tell you to sell it so of course im stuck on this mission. what do you guys think? check my save file below if you want to test it.
[my latest rdr1 save file.zip](https://github.com/CabooseSayzWTF/RDR1-Switch-and-PS4-Mod-Menu/files/13822454/my.latest.rdr1.save.file.zip)

**Comment by CabooseSayzWTF** [comment]
Will try to look into it but no promises that it will be fixed. Is this the only sp specific mod option you used (which is noted as use at your own risk which is a warning that save progression could break if you use any of those options on saves you care about), for future reference if you didn't make sure you back up your saves before ever using the menu.

**Comment by CabooseSayzWTF** [comment]
> this bug is currently occurred when you triggered the max money cheat on this trainer and i can't even pass the mission called John Marston and Son when you need to sell an Elk meat, it says selled when i try to sell the Elk meat but the objective is still trying to tell you to sell it so of course im stuck on this mission. what do you guys think? check my save file below if you want to test it. [my latest rdr1 save file.zip](https://github.com/CabooseSayzWTF/RDR1-Switch-and-PS4-Mod-Menu/files/13822454/my.latest.rdr1.save.file.zip)

Okay so this bug doesn't actually seem related to the menu at all. This is a random game bug that has been present since rdr1 release back on xbox 360 and ps3, you can take note of that here: https://gamefaqs.gamespot.com/ps3/957923-red-dead-redemption/answers/223082-the-mission-john-marston-and-son-the-general-store-the-yellow-dot-wont-disappear

Here's what I did to fix it on my end. Get to the point where you are about to sell the meat, shoot and kill the shopkeeper to fail the mission and then reload checkpoint which will put you outside of mazanita post. Do this 4 times to the point it says "Skip Checkpoint" on mission fail. Once you have skipped the checkpoint and return home with jack, replay the mission from the missions tab in stats menu and then once you get back to manzanita post sell all elk meat, all elk skin, and all elk antlers. It should now progress like normal. Hope this helps! I used your save and did this 3x times now back to back to triple check the steps and it worked everytime for me. In the case that if it for some reason does not work for you, I can re-do it on your supplied save and upload it here for you to continue playing on.

**Comment by AttarGangster2** [comment]
thank you for finding the solution and i hope this is work, best luck to you!
Edit: it works, now i can complete the game and thank you, well i thought the problem was the trainer
So again many many thanks.
